### ISSUE TITLE
Reordering Artboards in Layer list

### ISSUE THREAD

**Issue by nitrada** [bomberstudios/sketch-commands#18]
Hey there,

first of all thanks a lot for providing these very useful commands for Sketch! 
Very helpful in our everyday work.

I have something in my mind since quite some time that I think would totally enhance our workflow. It might be pretty specific, and the solution I have in mind not really possible with Sketch's current API, but I thought I just write it down here to start a conversation …

We're working with a lot of Artboards per Page. This happens both while exploring a broad range of drafts (duplicating Artboards for new iterations), but also when documenting our design. We're taking some time to refactor our documents every now and then – mostly manually order the Artboards on the Canvas from the upper left to the lower right.

Now the problem: we usually have a pretty well structured Canvas, upper left to lower right. But this –for sure– is not at all reflected in the Layer List (new/duplicated Artboards being added on top of currently selected Artboard -> layer model). So I was thinking if we have this clear order of Artboards on the Canvas, wouldn't it be great to have a command to re-order the Artboards representations in the Layer List accordingly? (First Artboard top left becomes first in the Layer List etc.)

(Also, it would be great to be able to expand/collapse all Artboards/Groups in the Layer List at once by pressing a modifier, just like in Photoshop – but I'm aware this is something that should be part of Sketch itself ;-)

Do you know what I mean? Looking forward to your thoughts!

Have a great Sunday,
Christophe

**Comment by Petros-** [comment]
Hey, sorry to resurrect an old thread but I just wanted to second the motion for a way to reorder the artboards in the layer list by geography within the canvas. First off, thanks for your work in bring us these great plugins! They make sketch doable for an Adobe veteran. I'm just picking up Sketch and one of the things I miss greatly from Illustrator is the auto-numbering that occurs with artboards. In Illustrator I create a new file with 50+ artboards, it automatically grids them, and I start making screens in order. Then I can pretty easily reorder them by cutting and pasting all the stuff inside one artboard and into another and the artboard numbering persists because it's automatic (tied to the artboard location which I don't change).

In Sketch Numberize gets me part of the way there, but the order of the numbers (which is important to me because it relates to the order of the flow I'm creating) depends on the order of the layer list which I generally don't like to bother with. Why should I have to reorder artboards on the canvas and then also reorder the layer stack? Sounds photoshoppy. Anyways, thanks again for the great work you've done and if you wanted to know whether there's anyone else out there who could use the layer-stack-reordering command, there is! :)

**Comment by bomberstudios** [comment]
Well, thanks for *resurrecting* this old thread : )

This is a prototype of something I'm working on at the moment:

![artboard-moving](https://cloud.githubusercontent.com/assets/3832/14408924/1708f286-ff08-11e5-8ff7-ebc1cce55b97.gif)

![artboard-moving-02](https://cloud.githubusercontent.com/assets/3832/14408940/65c651d4-ff08-11e5-9d4d-6cdf1c17f814.gif)

**Comment by Petros-** [comment]
Pretty sweet! I love the second idea too, where the artboards space themselves automatically.

**Comment by SUPK187** [comment]
Love this idea too!!

**Comment by nitrada** [comment]
3 yrs! great to see this come alive again. and this for sure is something that should be triggered by user events :)

**Comment by Moustachioz** [comment]
I love this idea too! Having the artboards automatically order in the layers list based on the order on screen would be awesome

**Comment by mrrocks** [comment]
This is awesome, can't wait to use the next iteration 👍

**Comment by moeffju** [comment]
Is any of this released in some usable form?

**Comment by bomberstudios** [comment]
Not yet, haven't found the time to cleanup what I have (I found some issues when working with non iPhone-sized Artboards : )

**Comment by micahdaigle** [comment]
I need this SO BAD right now. :) Thanks for working on it, @bomberstudios ! Any updates?

**Comment by Quisp** [comment]
+1 for this feature, resurrecting for 2017---

 Also if it could be used to reorder the layers within an art board would be helpful for documentation (so the order that page elements occur in the page is reflected by the stacking order in the Wireframe / Layers sidebar.) I end up spending a large amount of time re-ordering others' work when it's time to ship to the engineers.

Any new progress on the fix?

**Comment by duncanhoge** [comment]
@bomberstudios That prototype is amazing. I don't care so much about the artboard names changing as I do the layer list order to match the reordering that's going on with the artboards. 

(Although I think I'd probably use what you've prototyped too, I just haven't figured out how that would fit with my workflow.)

**Comment by bomberstudios** [comment]
Quick update: I've pushed my prototype plugin to https://github.com/bomberstudios/artboard-manager

Still some work to do, but it's definitely usable for iPhone-sized artboards
