### ISSUE TITLE
Not working "Move..." commands in 3.4

### ISSUE THREAD

**Issue by Chuckland** [bomberstudios/sketch-commands#59]
Moving commands don't work after 3.4 sketch update.

**Update:** As it turned out, sketch 3.4 works tricky with ```selection``` variable if several sketch files are opened

**Comment by bomberstudios** [comment]
Thanks for the report, will investigate! : )

**Comment by bomberstudios** [comment]
hi @Chuckland, can you please provide more details about this issue? I can't seem to replicate it.

If you could share a screencast / Console.app output that would be awesome : )

**Comment by kornikow** [comment]
@bomberstudios Hello! I have the same problem. As I noticed moving commands don't work if Sketch open in fullscreen mode. Can I help you with something else?

**Comment by bomberstudios** [comment]
@kornikow can you please share a screencast of the issue? Thanks!

**Comment by Chuckland** [comment]
Screencast: https://dl.dropboxusercontent.com/u/18435190/quickcast-29-10-2015-07-41-41.mp4
1. When 2 windows are open Move command doesn't work
2. After closing 1 window, Move command starts working

**Comment by bomberstudios** [comment]
Ok… I believe that's a bug we've just fixed in Sketch. It's pretty hard to reproduce reliably, so if you could could contact me privately at ale@bohemiancoding.com to continue the discussion there, that would be great : )

**Comment by einancunlu** [comment]
I believe this problem is not related to this plugin, it's a general bug which I started to see after 3.4 update. In new version, Sketch's window focus is corrupted as I guess. Sometimes it supposes you're on the other document, and so plugins seem like don't work. (It tries to apply the command on the other document.) 

Temporary fix I have found is opening a new Sketch file and closing it while your actual Sketch document is opened at the background. But when switch between your Sketch windows, the focus can be corrupted again and you need to repeat this solution. 

I discovered this when I run this command with "Custom Plugin" menu action:
var page = context.document.currentPage()
var artboards = page.artboards()
log(artboards)

It prints out artboards, and you can see that sometimes it prints wrong artboards.

**Comment by bomberstudios** [comment]
@einancunlu is right, it's a bug in Sketch and we're working to get it fixed. Thanks for the detailed steps, Emin, I'm now able to reproduce it reliable so a fix will be easy to test : )

**Comment by einancunlu** [comment]
You're welcome @bomberstudios, glad I could help. : )

**Comment by bomberstudios** [comment]
This is fixed in Sketch 3.4.4, so closing : )
